#
# Makefile for the Synaptics DSX touchscreen driver.
#

synaptics_dsx-objs = synaptics_dsx_rmi_hid_i2c.o \
		     synaptics_dsx_core.o \
		     synaptics_dsx_fw_update.o

obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX) += synaptics_dsx.o

